version: "3.7"

services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: sh -c 'npm install && npm run build && npm run start'
    ports:
      - "3000:3000"
